name: Deploy to AWS

on:
  push:
    branches: [ main ]

env:
  ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  deploy-qr-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push QR API
        working-directory: ./qr-api
        env:
          JWT_SECRET: ${{ secrets.JWT_QR_SECRET }}
          STATS_API_URL: ${{ secrets.STATS_API_URL }}
        run: |
          docker build -t qr-api --build-arg JWT_SECRET=$JWT_SECRET --build-arg STATS_API_URL=$STATS_API_URL .
          docker tag qr-api:latest $ECR_REGISTRY/qr-api:latest
          docker push $ECR_REGISTRY/qr-api:latest

      - name: Update Lambda QR API
        run: |
          aws lambda update-function-code \
            --function-name QRAPIFunction \
            --image-uri $ECR_REGISTRY/qr-api:latest \
            --region $AWS_REGION

      - name: Wait for Lambda code update to complete
        run: |
          aws lambda wait function-updated \
            --function-name QRAPIFunction \
            --region $AWS_REGION

      - name: Update Lambda Configuration
        run: |
          aws lambda update-function-configuration \
            --function-name QRAPIFunction \
            --region $AWS_REGION \
            --environment "Variables={JWT_SECRET=${{ secrets.JWT_QR_SECRET }},STATS_API_URL=${{ secrets.STATS_API_URL }}}"

  deploy-stats-api:
    runs-on: ubuntu-latest
    needs: deploy-qr-api
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Stats API
        working-directory: ./stats-api
        env:
          JWT_SECRET: ${{ secrets.JWT_STATS_SECRET }}
        run: |
          docker build -t stats-api --build-arg JWT_SECRET=$JWT_SECRET .
          docker tag stats-api:latest $ECR_REGISTRY/stats-api:latest
          docker push $ECR_REGISTRY/stats-api:latest

      - name: Update Lambda Stats API
        run: |
          aws lambda update-function-code \
            --function-name StatsAPIFunction \
            --image-uri $ECR_REGISTRY/stats-api:latest \
            --region $AWS_REGION

      - name: Wait for Lambda code update to complete
        run: |
          aws lambda wait function-updated \
            --function-name QRAPIFunction \
            --region $AWS_REGION

      - name: Update Lambda Configuration
        run: |
          aws lambda update-function-configuration \
            --function-name QRAPIFunction \
            --region $AWS_REGION \
            --environment "Variables={JWT_STATS_SECRET=${{ secrets.JWT_STATS_SECRET }}}"